[package]
name = "keyboard-scancodes"
version = "0.1.0"
authors = ["chris ricketts <chris.ricketts@steribar.com>"]
edition = "2018"

[[bin]]
name = "hidsim-rs"
path = "src/hidsim.rs"

[dependencies]
gen_layouts = { path = "gen_layouts" }
bytes = "0.4"
structopt = "0.2"
